services:
  db:
    # The default memory setting (64M) is not enough anymore due to the size of the database we import
    # https://stackoverflow.com/questions/56839975/docker-shm-size-dev-shm-resizing-shared-memory
    shm_size: 1g
    build:
      context: .
      dockerfile: ./docker/dev/postgres/Dockerfile
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - env.docker.local
    ports:
      - "${POSTGRESQL_PORT:-5432}:5432"
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - 6379:6379
  app:
    build:
        context: .
        dockerfile: ./docker/dev/django/Dockerfile
    command: ./docker/dev/django/entrypoint.sh
    volumes:
      - ./lemarche:/app/lemarche
      - ./config:/app/config
    env_file:
      - env.docker.local
    ports:
      - "8880:8880"
    depends_on:
      - db

volumes:
  postgres_data:
