version: "3.7"

services:
  postgres:
    container_name: bitoubi_postgres
    image: postgis/postgis:12-master
    volumes:
      - ./docker/dev/postgres/:/docker-entrypoint-initdb.d/
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - env.docker.local
    ports:
      - "6543:5432"

  bitoubi:
    container_name: bitoubi_django
    restart: always
    build:
        context: .
        target: dev
        dockerfile: ./Dockerfile
    command: ./docker/dev/entrypoint.sh
    volumes:
      - ./lemarche:/app/lemarche
      - ./config:/app/config
    environment:
        - DEBUG=true
    env_file:
      - env.docker.local
    ports:
      - "8880:8880"
    depends_on:
      - postgres

volumes:
  postgres_data:
