[tool.poetry]
name = "lemarche"
description = "Marché de l'inclusion"
version = "1.0"
authors = []

[tool.poetry.dependencies]
boto = "^2.49.0"
boto3 = "^1.20.24"
crawlerdetect = "0.1.4"
Django = "4.0.6"
django-anymail = "8.5"
django-better-admin-arrayfield = "^1.4.2"
django-bootstrap4 = "21.2"
django-ckeditor = "6.2.0"
django-compressor = "3.1"
django-cors-headers = "3.11.0"
django-environ = "0.8.1"
django-fieldsets-with-inlines = "0.6"
django-filter = "21.1"
django-formtools = "^2.3"
django-libsass = "0.9"
django-storages = "1.12.3"
djangorestframework = "3.13.1"
drf-spectacular = "0.21.1"
factory-boy = "3.2.1"
huey = "2.4.3"
psycopg2-binary = "2.9.3"
PyMySQL = "1.0.2"
python = "^3.9"
python-stdnum = "1.17"
redis = "^3.5.3"
requests = "^2.27.1"
selenium = "4.1.0"
sentry-sdk = "1.5.4"
wagtail = "^2.16.1"
whitenoise = "5.3.0"
xlwt = "1.3.0"
django-select2 = "^7.10.0"

[tool.poetry.dev-dependencies]
black = "22.3.0"
coverage = "5.5"
django-debug-toolbar = "3.2.4"
django-extensions = "3.1.5"
flake8 = "3.9.2"
ipython = "7.31.1"
isort = "5.10.1"
poethepoet = "0.12.2"
pre-commit = "2.17.0"
pyproject-flake8 = "0.0.1a2"
pytest-django = "4.5.2"

[tool.poetry.scripts]

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]

[tool.flake8]
# E203: Whitespace before ':', used to please Black in `yield items[i : i + n]`
# E266: Too many leading '#' for block comment
# W503: Line break occurred before a binary operator
max-line-length = 119
ignore = "E203, E266, W503"
max-complexity = 10

[tool.isort]
combine_as_imports = true
ensure_newline_before_comments = true
force_grid_wrap = 0
include_trailing_comma = true
known_first_party = "lemarche"
lines_after_imports = 2
line_length = 119
multi_line_output = 3
use_parentheses = true

[tool.black]
line-length = 119
target-version = ['py38', 'py39']
include = '\.pyi?$'

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "lemarche.settings.test"

[tool.poe.tasks]
export = { shell = "poetry export --without-hashes --output requirements/staging.txt" }
export_dev = { shell = "poetry export --without-hashes --dev --output requirements/dev.txt" }
flake8 = { shell = "pflake8 lemarche" }
isort = { shell = "isort ./lemarche/*.py" }
black = { shell = "black lemarche" }
clean_code = ["isort", "black"]
clean = { shell = "rm -r __pycache__/" }
