[tool.poetry]
name = "itou_c4_api"
version = "0.1.0"
description = "API du marché de l'Inclusion"
authors = ["pmontens <pieterjan@montens.net>"]
packages = [
    {include = "itou_c4_api"},
    {include = "itou_c4_api/**"},
]

[tool.poetry.dependencies]
python = "^3.9"
Django = "^3.2.1"
djangorestframework = "^3.12.4"
mysqlclient = "^2.0.3"
drf-spectacular = "^0.15.1"
psycopg2-binary = "^2.8.6"
hashids = "^1.3.1"
flake8 = "^3.9.2"

[tool.poetry.dev-dependencies]
isort = "^5.8.0"
pyproject-flake8 = "^0.0.1-alpha.2"
flake8 = "^3.9.2"
poethepoet = "^0.10.0"
black = "^21.5b2"
pytest-django = "^4.4.0"
factory-boy = "^3.2.0"

[tool.poetry.scripts]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.flake8]
# E203: Whitespace before ':', used to please Black in `yield items[i : i + n]`
# E266: Too many leading '#' for block comment
# W503: Line break occurred before a binary operator
max-line-length = 119
ignore = "E203, E266, W503"
max-complexity = 10

[tool.isort]
combine_as_imports = true
ensure_newline_before_comments = true
force_grid_wrap = 0
include_trailing_comma = true
known_first_party = "itou_c4_api"
lines_after_imports = 2
line_length = 119
multi_line_output = 3
use_parentheses = true
skip="migrations"

[tool.black]
line-length = 119
target-version = ['py38', 'py39']
include = '\.pyi?$'
exclude = '''
/(
  | migrations
)/

'''

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "itou_c4_api.pytest_settings"
# testpaths = [
#     "tests",
#     "integration",
# ]
# addopts = "--nomigrations --self-containted-html --junitxml=./tests/results/junit.xml"

[tool.poe.tasks]
export = { shell = "poetry export -f requirements.txt --output requirements.txt"}
flake8 = { shell = "pflake8 itou_c4_api"}
isort = { shell = "isort ./itou_c4_api/*.py"}
black = { shell = "black itou_c4_api"}
clean = ["isort", "black"]
migrate = { shell = "./manage.py migrate"}
makemigrations = { shell = "./manage.py makemigrations"}
