[tool.poetry]
name = "itou_c4_api"
version = "0.1.0"
description = "API du marché de l'Inclusion"
authors = ["pmontens <pieterjan@montens.net>"]

[tool.poetry.dependencies]
python = "^3.9"
Django = "^3.2.1"
djangorestframework = "^3.12.4"
mysqlclient = "^2.0.3"
drf-spectacular = "^0.15.1"
psycopg2-binary = "^2.8.6"
hashids = "^1.3.1"
flake8 = "^3.9.2"

[tool.poetry.dev-dependencies]
isort = "^5.8.0"
pyproject-flake8 = "^0.0.1-alpha.2"
flake8 = "^3.9.2"
poethepoet = "^0.10.0"
black = "^21.5b2"

[tool.poetry.scripts]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.flake8]
max-line-length = 120
extend-ignore = "E203,"
max-complexity = 10

[tool.isort]
profile = "hug"
src_paths = ["isort", "test"]

[tool.black]
line-length = 120
target-version = ['py38', 'py39']
include = '\.pyi?$'

[tool.poe.tasks]
export = { shell = "poetry export -f requirements.txt --output requirements.txt"}
flake8 = { shell = "pflake8 itou_c4_api"}
isort = { shell = "isort --check-only itou_c4_api"}
black = { shell = "black --check itou_c4_api"}
clean = ["flake8", "isort", "black"]
