name: Prod Deploy

on:
  # Only manuel deployment for now
  workflow_dispatch:

# See https://github.com/marketplace/actions/deploy-to-clever-cloud
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Get source
    - name: Local shallow copy
      run: git fetch --prune --unshallow

    # Deploy to clever cloud
    - name: Deploy to Staging
      uses: PieterjanMontens/actions-clever-cloud@master
      with:
        appID: ${{ secrets.APP_PROD }}
      env:
        CLEVER_TOKEN: ${{ secrets.CLEVER_TOKEN }}
        CLEVER_SECRET: ${{ secrets.CLEVER_SECRET }}
